app/models/models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(120), nullable=False, unique=True)
    color = db.Column(db.String(120))
    password_hash = db.Column(db.String(120), nullable=False)
    date_added = db.Column(db.DateTime, default=datetime.utcnow())

    def __repr__(self):
        return f'<Name {self.name}>'

    def save_db(self):
        db.session.add(self)
        db.session.commit()


class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    author = db.Column(db.String(255))
    content = db.Column(db.String)
    slug = db.Column(db.String)
    submit= db.Column(db.String)
    date_posted = db.Column(db.DateTime, default=datetime.utcnow())

    def save_db(self):
        db.session.add(self)
        db.session.commit()

app/models/wtfforms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, PasswordField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea


class NameForm(FlaskForm):
    name = StringField("What's your name", validators=[DataRequired()])
    submit = SubmitField('Submit')


class UserForm(FlaskForm):
    name = StringField("What's your name", validators=[DataRequired()])
    email = EmailField("What's your email", validators=[DataRequired()])
    color = StringField("What's your favorite color")
    password = PasswordField('Password: ', validators=[DataRequired()])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    title = StringField('Title')
    content = StringField('Content', validators=[DataRequired()], widget=TextArea())
    author = StringField('Author', validators=[DataRequired()])
    slug = StringField('Slug', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask, render_template

app = Flask(__name__)
app.config.from_pyfile('config.py')

from app.models.models import db
db.init_app(app)
with app.app_context():
    db.create_all()

from app.utils.migration import migrate
migrate.init_app(app, db)

from app.utils.sessions import session
session.init_app(app)

from app.utils.bcrypt import bcrypt
bcrypt.init_app(app)

from app.routes.auth import auth_bp
app.register_blueprint(auth_bp)

from app.routes.base import base_bp
app.register_blueprint(base_bp)


# Creating Error Pages
@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html', title='404 ERROR'), 404

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.models.wtfforms import UserForm
from app.models.models import User, db
from app.utils.bcrypt import bcrypt
from app.utils.sessions import session

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/home')
@auth_bp.route('/')
def index():
    return render_template('index.html', title='Home Page')


@auth_bp.route('/user/<name>')
def user_profile(name):
    return render_template('user.html', name=name, title='User Profile')


@auth_bp.route('/add', methods=['GET', 'POST'])
def add_user():
    name = None
    form = UserForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            color = form.color.data if form.color.data else None  # Return None if color is not provided
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            new_user = User(name=form.name.data, email=form.email.data, color=color, password_hash=hashed_password)
            new_user.save_db()
        name = form.name.data
        form.name.data = ""
        form.email.data = ""
        form.color.data = ""
    our_users = User.query.order_by(User.date_added)
    flash("User added successfully", 'success')
    return render_template('add_user.html', form=form, title='Add User', name=name, our_users=our_users)


@auth_bp.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    form = UserForm()
    name_to_update = User.query.get_or_404(id)
    if request.method == 'POST':
        name_to_update.name = request.form.get('name')
        name_to_update.email = request.form.get('email')
        name_to_update.color = request.form.get('color')

        try:
            db.session.commit()
            flash("User Updated Successfully", 'success')
            return redirect(url_for('auth.add_user'))
        except:
            flash("An error occurred while updating the user", 'error')
    return render_template('update.html', form=form, name_to_update=name_to_update)


@auth_bp.route("/delete/<int:id>", methods=['GET', 'POST'])
def delete(id):
    user_to_delete = User.query.get_or_404(id)
    name = None
    form = UserForm()
    try:
        db.session.delete(user_to_delete)
        db.session.commit()
        flash('User Deleted Successfully', 'success')
        our_users = User.query.order_by(User.date_added)
        return render_template('add_user.html', form=form, name=name, our_users=our_users)
    except:
        flash('Whooops! There was a problem while deleting user, try again!', 'error')
        return render_template('add_user.html', form=form, name=name, our_users=our_users)

app/routes/base.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.models.wtfforms import NameForm, PostForm
from app.models.models import Posts, db

base_bp = Blueprint('base', __name__)


@base_bp.route('/name', methods=['GET', 'POST'])
def name_form():
    form = NameForm()
    name = None
    if form.validate_on_submit():
        name = form.name.data
        flash("Form Submitted Successfully", "success")
    return render_template('name.html', form=form, name=name, title='Name')


@base_bp.route('/add-post', methods=['GET', 'POST'])
def add_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Posts(
            title=form.title.data,
            author=form.author.data,
            content=form.content.data,
            slug=form.slug.data,
            submit=form.submit.data
        )

        # Saving to database
        db.session.add(post)
        db.session.commit()

        flash('Post has been created successfully', 'success')
        return redirect(url_for('base.post_page'))  # Redirect to the post_page route after successful submission

    return render_template('posts/add_post.html', form=form, title='Add Post')


@base_bp.route('/post_page', methods=['GET', 'POST'])
def post_page():
    posts = Posts.query.all()
    return render_template('posts/posts.html', posts=posts)


@base_bp.route('/post_page/<int:id>')
def post(id):
    post = Posts.query.get_or_404(id)
    return render_template('posts/post.html', post=post, title=f"Post{id}")


@base_bp.route('/edit-post/<int:id>', methods=['GET', 'POST'])
def edit_post(id):
    post = Posts.query.get_or_404(id)
    form = PostForm(obj=post)

    if form.validate_on_submit():
        form.populate_obj(post)
        db.session.commit()
        flash('Post has been updated successfully', 'success')
        return redirect(url_for('base.post_page'))  # Redirect to the post_page route after successful update

    return render_template('posts/edit_post.html', form=form, title='Edit Post', post=post)


@base_bp.route('/delete-post/<int:id>')
def delete_post(id):
    post = Posts.query.get_or_404(id)
    db.session.delete(post)
    db.session.commit()

    flash('Post Has Been Deleted', 'success')
    return redirect(url_for('base.post_page'))

app/templates/add_user.html
{% extends 'components/layout.html' %}
{% block content %}
    <div class="shadow p-3 mb-5 bg-body rounded">
        <h1>User List: </h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}

            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}<br>

            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}<br>

            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }}<br>

            {{ form.color.label(class="form-label") }}
            {{ form.color(class="form-control") }}<br>

            {{ form.submit(class="btn btn-primary") }}
        </form>

    </div>
    <table class="table table-hover table-bordered table-striped">
    {% for our_user in our_users %}
            <tr>
            <td>{{ our_user.id }}. <a href="{{ url_for('auth.update', id=our_user.id) }}">{{ our_user.name }}</a> - {{ our_user.email }} - {{ our_user.color }}
                <a href="{{ url_for('auth.delete', id=our_user.id) }}">Delete</a>
            </td>
            </tr>
        {% endfor %}
    </table>
    <br><br>

{% if request.method == 'POST' %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    Swal.fire({
                        icon: '{{ category }}',
                        title: '{{ message }}',
                        showConfirmButton: true,
                    });
                {% endfor %}
            {% endif %}
        {% endwith %}
    </script>
{% endif %}
{% endblock %}

app/templates/base/register.html
{% extends 'components/layout.html' %}

{% block component %}

{% endblock component %}

app/templates/components/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>Reddit - {{ title }}</title>
    {% else %}
        <title>Reddit</title>
    {% endif %}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/photo.jpg') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% include 'components/navbar.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/templates/components/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/navbar.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-light" id="neubar">
    <div class="container">
        <img src="{{ url_for('static', filename='images/photo.jpg') }}" height="60" width=70">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto ">
                <li class="nav-item">
                    <a class="nav-link mx-2 active" aria-current="page" href="{{ url_for('auth.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-2" href="{{ url_for('base.name_form') }}">Name</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-2" href="{{ url_for('base.add_post') }}">Add Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-2" href="{{ url_for('base.post_page') }}">Posts</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link mx-2" href="{{ url_for('auth.add_user') }}">Add User</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{{ url_for('auth.user_profile', name='Jamal') }}">User
                            Profile</a></li>
                        <li><a class="dropdown-item" href="#">About Us</a></li>
                        <li><a class="dropdown-item" href="#">Contact us</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
</html>

app/templates/index.html
{% extends 'components/layout.html' %}

{% block content %}
    <h1>hello</h1>
    <img src="{{ url_for('static', filename='images/c57.gif') }}">
{% endblock %}

app/templates/name.html
{% extends 'components/layout.html' %}

{% block content %}
<br>
{% if request.method == 'POST' %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    Swal.fire({
                        icon: '{{ category }}',
                        title: '{{ message }}',
                        showConfirmButton: true,
                    });
                {% endfor %}
            {% endif %}
        {% endwith %}
    </script>
{% endif %}

{% if name %}
    <h1>Hello {{ name }}</h1>
{% else %}
    <h1>What's your name?</h1><br>
    <form action="" method="post">
        {{ form.hidden_tag() }}

        {{ form.name.label(class="form-label") }}
        {{ form.name(class="form-control") }}<br>
        {{ form.submit(class="btn btn-primary") }}
    </form>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

app/templates/posts/add_post.html
{% extends 'components/layout.html' %}

{% block content %}
    <br>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <h1>Adding Posts:</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}

            <div class="mb-3">
                {{ form.title.label(class="form-label") }}
                {{ form.title(class="form-control") }}
            </div>

            <div class="mb-3">
                {{ form.author.label(class="form-label") }}
                {{ form.author(class="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.slug.label(class="form-label") }}
                {{ form.slug(class="form-control") }}
            </div>

            <div class="mb-3">
                {{ form.content.label(class="form-label") }}
                {{ form.content(class="form-control", rows="5") }}
            </div>

            <div class="mb-3">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/posts/edit_post.html
{% extends 'components/layout.html' %}

{% block content %}
    <br>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <h1>Edit Post:</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}

            <div class="mb-3">
                {{ form.title.label(class="form-label") }}
                {{ form.title(class="form-control") }}
            </div>

            <div class="mb-3">
                {{ form.author.label(class="form-label") }}
                {{ form.author(class="form-control") }}
            </div>

            <div class="mb-3">
                {{ form.content.label(class="form-label") }}
                {{ form.content(class="form-control", rows="5") }}
            </div>

            <div class="mb-3">
                {{ form.slug.label(class="form-label") }}
                {{ form.slug(class="form-control") }}
            </div>

            <div class="mb-3">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/posts/post.html
{% extends 'components/layout.html' %}

{% block content %}
   <br>
   <div class="shadow p-3 mb-5 bg-body rounded">
       <h2>{{ post.title }}</h2><br>
       By: {{ post.author }} | {{ post.date_posted }}<br>
       <hr>
       {{ post.content }}<br><br>
       <br>
       <a href="{{ url_for('base.post_page') }}" class="btn btn-outline-secondary btn-sm">Return Back</a>
   </div><br>
{% endblock %}

app/templates/posts/posts.html
{% extends 'components/layout.html' %}

{% block content %}<br>
   {% for post in posts %}
   <div class="shadow p-3 mb-5 bg-body rounded">
   <h2>{{ post.title }}</h2><br>
      By: {{ post.author }} | {{ post.date_posted }}<br>
      <hr>
      {{ post.content }}<br><br>
      <br>
      <a href="{{ url_for('base.post', id=post.id) }}" class="btn btn-outline-secondary btn-sm">View page</a>
      <a href="{{ url_for('base.edit_post', id=post.id) }}" class="btn btn-outline-dark btn-sm">Edit page</a>
      <a href="{{ url_for('base.delete_post', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete page</a>
      </div><br>
   {% endfor %}
{% endblock %}

app/templates/update.html
{% extends 'components/layout.html' %}
{% block content %}
{% if name %}
    <h1 style="font-family: 'Dancing Script', cursive; color: #007bff;">User Updated Successfully!</h1>
    <table class="table table-hover table-bordered table-striped">
        <tr>
            <td>{{ name_to_update.id }}. {{ name_to_update.name }} - {{ name_to_update.email }}</td>
        </tr>
    </table>
{% else %}
    <br>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <h1>Update User!</h1>
        <form action="{{ url_for('auth.update', id=name_to_update.id) }}" method="post">
            {{ form.hidden_tag() }}

            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", value=name_to_update.name) }}<br>

            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control", value=name_to_update.email) }}<br>

            {{ form.color.label(class="form-label") }}
            {{ form.color(class="form-control", value=name_to_update.color) }}<br>

            {{ form.submit(class="btn btn-primary") }}

            <!-- Кнопка для возврата на страницу добавления пользователя -->
            <a href="{{ url_for('auth.add_user') }}" class="btn btn-primary btn-success">← Go back</a>
            <!-- Кнопка для удаления пользователя -->
        </form>
    </div>
{% endif %}
{% if request.method == 'POST' %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    Swal.fire({
                        icon: '{{ category }}',
                        title: '{{ message }}',
                        showConfirmButton: true,
                    });
                {% endfor %}
            {% endif %}
        {% endwith %}
    </script>
{% endif %}
{% endblock %}

app/templates/user.html
{% extends 'components/layout.html' %}
{% block content %}
<h1>Hello {{ name|title }}</h1>
{% endblock content %}